[config]
reload_apps = false
set_wallpaper = false

[config.custom_colors.red]
color = "#FF0000"
blend = true

[config.custom_colors.green]
color = "#00FF00"
blend = true

[config.custom_colors.yellow]
color = "#FFFF00"
blend = true

[config.custom_colors.blue]
color = "#0000FF"
blend = true

[config.custom_colors.magenta]
color = "#FF00FF"
blend = true

[config.custom_colors.cyan]
color = "#00FFFF"
blend = true

[config.custom_colors.white]
color = "#FFFFFF"
blend = true

[config.custom_colors.orange]
color = "#FF5800"
blend = true

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.css"
output_path = "~/.config/waybar/colors.css"
post_hook = "killall -q -SIGUSR2 waybar || true"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland.conf"
output_path = "~/.config/hypr/colors.conf"
post_hook = "hyprctl reload"

[templates.niri]
input_path = "~/.config/matugen/templates/niri.kdl"
output_path = "~/.config/niri/colors.kdl"
post_hook = "niri msg action load-config-file"

[templates.cava]
input_path = "~/.config/matugen/templates/cava"
output_path = "~/.config/cava/config"
post_hook = "killall -q -SIGUSR1 cava || true"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty.conf"
output_path = "~/.config/kitty/colors.conf"
post_hook = "killall -q -SIGUSR1 kitty || true"

[templates.dunst]
input_path = "~/.config/matugen/templates/dunstrc"
output_path = "~/.config/dunst/dunstrc"
post_hook = "dunstctl reload && notify-send 'updated'"

[templates.tmux]
input_path = "~/.config/matugen/templates/tmux.conf"
output_path = "~/.tmux-colors.conf"
post_hook = "tmux source-file ~/.tmux.conf"

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'

# [templates.gtk4]
# input_path = '~/.config/matugen/templates/gtk-colors.css'
# output_path = '~/.config/gtk-4.0/gtk.css'
