backend = "fastresize"
color_space = "lch"
palette = "softdark16"

[templates]
kitty = { template = 'kitty.conf', target = '~/.config/kitty/colors.conf' }
rofi = { template = 'rofi.rasi', target = '~/.config/rofi/colors.rasi' }
tmux = { template = 'tmux.conf', target = '~/.tmux-colors.conf' }
cava = { template = "cava", target = "~/.config/cava/config" }
dunst = { template = 'dunstrc', target = '~/.config/dunst/dunstrc' }
niri = { template = "niri.kdl", target = "~/.config/niri/colors.kdl" }
waybar = { template = 'waybar.css', target = '~/.config/waybar/colors.css' }
# gtk3 = { template = 'gtk.css', target = "~/.config/gtk-3.0/gtk.css" }
# gtk4 = { template = 'gtk.css', target = "~/.config/gtk-4.0/gtk.css" }
